const SET_IMAGE = 'SET_IMAGE'
const SET_TITLE = 'SET_TITLE'
const SET_PRICE = 'SET_PRICE'
const SET_DISCOUNT = 'SET_DISCOUNT'
const SET_DIS_PRICE = 'SET_DIS_PRICE'
const SAVE_PRODUCT = 'SAVE_PRODUCT'

export {
    SET_IMAGE,
    SET_TITLE,
    SET_PRICE,
    SET_DISCOUNT,
    SET_DIS_PRICE,
    SAVE_PRODUCT,
}